#! /bin/bash


# +------------------------------------------------------------------------------------+ #
# |                                  SLURM PARAMETERS                                  | #
# +------------------------------------------------------------------------------------+ #

#SBATCH -p publicgpu -A miv
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 1
#SBATCH --gres=gpu:1
#SBATCH --mem=16G
#SBATCH --constraint="gpua100|gpurtx6000|gpurtx5000|gpuv100"
#SBATCH -o jobs/DEV_b=5.out


# +------------------------------------------------------------------------------------+ #
# |                                ENVIRONNEMENT SET UP                                | #
# +------------------------------------------------------------------------------------+ #

module load python/Anaconda3-2019
module load cuda/cuda-11.8
module load gcc/gcc-11
source /usr/local/Anaconda/Anaconda3-2019.07/etc/profile.d/conda.sh
conda deactivate
conda activate torch2cu118
cd /home/vedrenne/Documents/Side_Projects/tessti


# +------------------------------------------------------------------------------------+ #
# |                                 RUN PYTHON SCRIPT                                  | #
# +------------------------------------------------------------------------------------+ #

python schedule.py --config jobs/DEV_b=5.toml
